In [1]:
#advantage- less size,high speed(arrithmatic and vector &matrix operations are fast,SciPy and NumPy have optimized functions such as linear algebra operations
#matrix operation,homogenous data
#numpy array are of fixed size changing the size can create a different array
#The optimized C code numpy/scipy use behind the scenes consists of the atlas,blas
#list size -   64 + 8 * len(lst) + + len(lst) * 28
#numpy error - 96 + n * 8 Bytes
#support elemet wise addition multiplication

#shape(),ndim(),itemsize()
#one tuple one row next in next row

In [5]:
import numpy as np
#b added to each row of a
a= np.array([(1,2,3),(2,3,4)])
b= np.array([(1,2,3)])
a+b

array([[2, 4, 6],
       [3, 5, 7]])

In [12]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [6]:
#for selecting 0th row twice
print(a[[0,0]],a[0],a[0,1])

[[1 2 3]
 [1 2 3]] [1 2 3] 2


In [5]:
import numpy as np
import time
import sys
#addition of two array , adding a constant
a= np.array([(1,2,3),(2,3,4)])
b= np.array([(1,2,3),(2,3,4)])
print(a+b,'********',a+2)

[[2 4 6]
 [4 6 8]] ******** [[3 4 5]
 [4 5 6]]


In [7]:
a= np.array([(1,2,3),(2,3,4)])
b= np.array([(1,2,3),(2,3,4)])
np.hstack(a)

array([1, 2, 3, 2, 3, 4])

In [18]:
#ravel() combine all tuple elements - vstack(added vertically)- hstack(added horizo))
print(a,'*******',a.ravel(),'****',np.vstack((a,b)),'*****',np.hstack((a,b)))

[[1 2 3]
 [2 3 4]] ******* [1 2 3 2 3 4] **** [[1 2 3]
 [2 3 4]
 [1 2 3]
 [2 3 4]] ***** [[1 2 3 1 2 3]
 [2 3 4 2 3 4]]


In [20]:
#for sum give the axis=, linspace included last element as well,a[row ,col]
a= np.array([(1,2,3),(2,3,4)])
b= np.array([(1,2,3),(2,3,4)])
print(a/b,'****',a.sum(axis=1),'*****',np.linspace(2,5,5),'****',a[0:,2])

[[1. 1. 1.]
 [1. 1. 1.]] **** [6 9] ***** [2.   2.75 3.5  4.25 5.  ] **** [3 4]


In [19]:
a= np.array([(1,2,3),(2,3,4),(3,5,6)])
np.repeat(a, 2)

array([1, 1, 2, 2, 3, 3, 2, 2, 3, 3, 4, 4, 3, 3, 5, 5, 6, 6])

In [23]:
print(np.zeros((10, )),np.ones((7,)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] [1. 1. 1. 1. 1. 1. 1.]


In [27]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [36]:
a

array([[1, 2, 3],
       [2, 3, 4],
       [3, 5, 6]])

In [24]:
print(a[0][1],a[0,1],a[0],a[2],'qqq',a[:2,:2])

IndexError: index 2 is out of bounds for axis 0 with size 2

In [15]:
#execution time difference in two arrays
#s=arange(1000)
#sys.getsizeof(5)*len(s)
size = 100
l1=range(size)
l2=range(size)

a1=np.arange(size)
a2=np.arange(size)

start = time.time()
result = [(x,y) for x,y in zip(l1,l2)]
print(result)
print((time.time()-start)*100000)

start = time.time()
result = a1+a2
print(result)
print((time.time()-start)*100000)



[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36), (37, 37), (38, 38), (39, 39), (40, 40), (41, 41), (42, 42), (43, 43), (44, 44), (45, 45), (46, 46), (47, 47), (48, 48), (49, 49), (50, 50), (51, 51), (52, 52), (53, 53), (54, 54), (55, 55), (56, 56), (57, 57), (58, 58), (59, 59), (60, 60), (61, 61), (62, 62), (63, 63), (64, 64), (65, 65), (66, 66), (67, 67), (68, 68), (69, 69), (70, 70), (71, 71), (72, 72), (73, 73), (74, 74), (75, 75), (76, 76), (77, 77), (78, 78), (79, 79), (80, 80), (81, 81), (82, 82), (83, 83), (84, 84), (85, 85), (86, 86), (87, 87), (88, 88), (89, 89), (90, 90), (91, 91), (92, 92), (93, 93), (94, 94), (95, 95), (96, 96), (97, 97), (98, 98), (99, 99)]
199.98550415039062


In [6]:
import random
random.randint(0, 10) 
#randint(1,100)

2

In [8]:
for i in range(10):
    print(random.randint(0,10))

0
3
7
0
3
0
2
5
9
0


In [9]:
for i in range(10):
    print(random.choice(range(10)))

3
5
3
0
6
9
1
5
0
9


In [22]:
a=[1,2,3,4,5,6,7,8]
random.shuffle(a)
a

[4, 1, 8, 3, 6, 2, 5, 7]

In [21]:
random.sample(a, 5)

[6, 7, 2, 8, 5]

In [11]:
random.uniform(2, 10)

8.487873366097435