In [4]:
import numpy as np
a=np.random.randn(5,5)/np.sqrt(5)
b=np.random.randn(5,5)

In [5]:
print(a)
print(b)

[[-0.08469883  1.03158592  0.48194186 -0.2204184   0.22438996]
 [ 0.22327049  0.60129905 -0.14209678 -0.24982718  0.01376406]
 [ 0.29880362  0.590983   -0.67989421  0.01097859 -0.27118234]
 [ 0.66742475  0.3587954   0.24266685 -0.42853061  0.04668058]
 [-0.24802881  0.35265335  0.19403171  0.39026051 -0.08129911]]
[[-0.81164502  0.91899064 -1.05607409 -0.87524498 -0.63760737]
 [ 2.64633671 -0.22560848  0.84156456  0.4348585  -1.45298815]
 [-0.00860838  0.18413727 -0.69981872 -0.4672101  -1.48338406]
 [ 1.12873553  0.21375455  0.45502941 -0.16613066  0.47857671]
 [ 0.32424934  1.05725937  0.46884157 -0.22516898  0.54658554]]


In [28]:
for sentence in sentences:
     
#        sentence = [start_idx] + sentence +[end_idx]
        n = len(sentence)
        print(n)
        inputs = np.zeros((n-1,10))
        targets  = np.zeros((n-1,10))
        inputs[np.arange(n-1),sentence[:n-1]] =1
        targets[np.arange(n-1),sentence[1:]] = 1

TypeError: iteration over a 0-d array

In [13]:
np.arange(5-1)

array([0, 1, 2, 3])

In [46]:
x = np.array([[1,2,3,1,2,3,4],[5,6,7,1,2,3,4],[8,9,10,1,5,6,7],[4,11,12,1,8,9,0]])

In [47]:
b=x[[1,2,3],[4,5,6]]

In [48]:
b

array([2, 6, 0])

In [51]:
c=x[[0,0]]
c

array([[1, 2, 3, 1, 2, 3, 4],
       [1, 2, 3, 1, 2, 3, 4]])